#!/usr/bin/env bash
#
# SessionEnd Hook - Demonstrates session cleanup and summary generation
#
# Learning Objectives:
# 1. Understand when sessions end
# 2. Analyze session activity
# 3. Generate session summaries
# 4. Clean up temporary state
#

set -euo pipefail

# Get script directory and source utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/logger.sh"
source "${SCRIPT_DIR}/../lib/context-builder.sh"

# Start logging
log_hook_event "SessionEnd" "Session Termination" "Claude Code session is ending"

# Log what we're learning
log_message "LEARNING" "${COLOR_CYAN}" "━━━ LEARNING: SessionEnd Hook ━━━"
log_message "LEARNING" "${COLOR_CYAN}" "This hook runs when Claude Code session ends"
log_message "LEARNING" "${COLOR_CYAN}" "Use it to: save state, generate summaries, cleanup resources"
log_separator

# Find the most recent session metadata
log_message "STEP" "${COLOR_BLUE}" "Step 1: Locating session metadata"
sessions_dir="${HOME}/.claude/hooks-lab/sessions"
if [[ -d "${sessions_dir}" ]]; then
    latest_session=$(ls -t "${sessions_dir}" | head -1 2>/dev/null || echo "")
    if [[ -n "${latest_session}" ]]; then
        session_file="${sessions_dir}/${latest_session}"
        log_success "Found session metadata: ${latest_session}"

        # Read session data
        session_id=$(jq -r '.session_id' "${session_file}" 2>/dev/null || echo "unknown")
        started_at=$(jq -r '.started_at' "${session_file}" 2>/dev/null || echo "unknown")

        log_context "Session ID" "${session_id}"
        log_context "Started At" "${started_at}"
    else
        log_context "Session" "No session metadata found"
    fi
else
    log_context "Session" "No sessions directory found"
fi
log_separator

# Analyze tool usage
log_message "STEP" "${COLOR_BLUE}" "Step 2: Analyzing tool usage during session"
tool_usage_log="${HOME}/.claude/hooks-lab/tool-usage.log"
if [[ -f "${tool_usage_log}" ]]; then
    # Count tool uses
    total_tools=$(wc -l < "${tool_usage_log}" 2>/dev/null || echo 0)
    log_context "Total Tool Uses" "${total_tools}"

    # Show most used tools
    if [[ ${total_tools} -gt 0 ]]; then
        log_message "INFO" "${COLOR_BLUE}" "Most used tools this session:"
        # Get unique tool names and count them
        awk -F',' '{print $2}' "${tool_usage_log}" | sort | uniq -c | sort -rn | head -5 | while read count tool; do
            log_context "  ${tool}" "${count} uses"
        done
    fi
else
    log_context "Tool Usage" "No tool usage data available"
fi
log_separator

# Calculate session duration
log_message "STEP" "${COLOR_BLUE}" "Step 3: Calculating session duration"
if [[ -n "${started_at:-}" ]] && [[ "${started_at}" != "unknown" ]]; then
    start_epoch=$(date -d "${started_at}" +%s 2>/dev/null || echo 0)
    end_epoch=$(date +%s)
    duration=$((end_epoch - start_epoch))

    hours=$((duration / 3600))
    minutes=$(((duration % 3600) / 60))
    seconds=$((duration % 60))

    log_context "Session Duration" "${hours}h ${minutes}m ${seconds}s"
else
    log_context "Session Duration" "Unknown"
fi
log_separator

# Update session metadata with end info
log_message "STEP" "${COLOR_BLUE}" "Step 4: Updating session metadata"
if [[ -n "${session_file:-}" ]] && [[ -f "${session_file}" ]]; then
    # Update the session file with end information
    tmp_file=$(mktemp)
    jq ". + {ended_at: \"$(date -Iseconds)\", duration_seconds: ${duration:-0}}" "${session_file}" > "${tmp_file}"
    mv "${tmp_file}" "${session_file}"
    log_success "Session metadata updated with end time"
else
    log_context "Metadata Update" "No session file to update"
fi
log_separator

# Generate session summary
log_message "STEP" "${COLOR_BLUE}" "Step 5: Generating session summary"
summary_file="${HOME}/.claude/hooks-lab/session-summary.txt"
cat > "${summary_file}" <<EOF
═══════════════════════════════════════════════════════════
CLAUDE CODE SESSION SUMMARY
═══════════════════════════════════════════════════════════

Session ID:      ${session_id:-unknown}
Started:         ${started_at:-unknown}
Ended:           $(date -Iseconds)
Duration:        ${hours:-0}h ${minutes:-0}m ${seconds:-0}s
Working Dir:     ${PWD}

Tool Usage:      ${total_tools:-0} total tool invocations

═══════════════════════════════════════════════════════════
This summary was generated by hooks-lab SessionEnd hook
Log file: ${LOG_FILE}
═══════════════════════════════════════════════════════════
EOF

log_success "Session summary saved to: ${summary_file}"
log_separator

# Display final summary
log_hook_event "SessionEnd" "Complete" "Session cleanup and summary generation successful"
log_message "SUMMARY" "${COLOR_GREEN}" "Session ended gracefully"
log_message "SUMMARY" "${COLOR_GREEN}" "Summary: ${summary_file}"
log_message "SUMMARY" "${COLOR_CYAN}" "Full logs: ${LOG_FILE}"

echo ""
echo -e "${COLOR_MAGENTA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
echo -e "${COLOR_GREEN}🧪 Hooks Lab: SessionEnd hook executed successfully${COLOR_RESET}"
echo -e "${COLOR_GRAY}Session analysis complete. Thank you for using hooks-lab!${COLOR_RESET}"
echo -e "${COLOR_MAGENTA}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
echo ""

# Success exit
exit 0
